version: '3.8'
services:
  studio-lite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Streamlit
      - "5000:5000"  # Flask API
    env_file:
      - .env
    volumes:
      - .:/app
